In [1]:
import numpy

In [2]:
import numpy as np
a=np.diag([1,4,8,9])
a

array([[1, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 8, 0],
       [0, 0, 0, 9]])

In [8]:
''' .randit ==> this function is used to generate
    a random numbers between a given range'''

a=np.random.randint(1,10,4)
a

array([6, 5, 7, 1])

In [10]:
''' rand() ==> this function is used to generate 
    random number between 0 to 1
    syntax ==> rand(number of value)
'''
a=np.random.rand(5)
a

array([0.31887888, 0.33395952, 0.19726222, 0.97819619, 0.05139077])

In [11]:
''' randn() ==> this function is used to generate a random 
    number from -3 to close 3 .this may return
    positive or negative as well
    syntax
'''

' randn() ==> this function is used to generate a random \n    number from -3 to close 3 .this may return\n    positive or negative as well\n    syntax\n'

In [13]:
''' reshaping data '''
a = np.random.randint(1,50,12)
a

array([ 1, 32, 19, 34, 46, 19, 44, 12, 18, 20, 20, 37])

In [14]:
''' n(rows) * n(coulumn) = (total element)
'''
a.shape

(12,)

In [15]:
a.reshape(2,6)

array([[ 1, 32, 19, 34, 46, 19],
       [44, 12, 18, 20, 20, 37]])

In [16]:
a.reshape(3,4)

array([[ 1, 32, 19, 34],
       [46, 19, 44, 12],
       [18, 20, 20, 37]])

In [17]:
# principle of -1
a= a.reshape(-1,4)
a

array([[ 1, 32, 19, 34],
       [46, 19, 44, 12],
       [18, 20, 20, 37]])

In [18]:
a= a.reshape(3,-1)
a

array([[ 1, 32, 19, 34],
       [46, 19, 44, 12],
       [18, 20, 20, 37]])

In [19]:
''' seed function()
'''
np.random.seed(5)
a = np.random.randint(1,100,10)
a

array([79, 62, 17, 74,  9, 63, 28, 31, 81,  8])

In [21]:
''' VIEW vs COPY
'''
# view 
a=np.array([10,20,30,40,50,60,70,80])
b=a[3:6]
b[:]=0
a

array([10, 20, 30,  0,  0,  0, 70, 80])

In [22]:
# copy 
a=np.array([10,20,30,40,50,60,70,80])
b=a[3:6].copy()
b[:]=0
a

array([10, 20, 30, 40, 50, 60, 70, 80])

In [23]:
b

array([0, 0, 0])

In [24]:
''' conditional statemeent
'''
a=np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [25]:
a%2

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [26]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [27]:
a<10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False])

In [28]:
a%2==0

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False])

In [30]:

a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14])

In [31]:
# operation on array
a=[1,2,3,4,5]
a=np.array(a)


In [32]:
a*2

array([ 2,  4,  6,  8, 10])

In [33]:
a**2

array([ 1,  4,  9, 16, 25])

In [34]:
a**3


array([  1,   8,  27,  64, 125], dtype=int32)

In [37]:
b=np.array([1,2,3,4]).reshape(2,2)
b

array([[1, 2],
       [3, 4]])

In [36]:
a=np.array([5,6,7,8]).reshape(2,2)
a

array([[5, 6],
       [7, 8]])

In [38]:
a

array([[5, 6],
       [7, 8]])

In [39]:
a+b

array([[ 6,  8],
       [10, 12]])

In [40]:
b/a

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [41]:
b-a

array([[-4, -4],
       [-4, -4]])

In [42]:
a.dot(b)

array([[23, 34],
       [31, 46]])

In [43]:
''' some more important numpy functions
'''
np.max(a)

8

In [44]:
np.argmin(a)

0

In [45]:
np.argmax(a)

3

In [46]:
np.sqrt(a)

array([[2.23606798, 2.44948974],
       [2.64575131, 2.82842712]])

In [47]:
np.sin(a)

array([[-0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825]])

In [51]:
''' linspace() ==> this function returns value between a given
    range and with a same gap between consicutive elements.
'''
a=np.linspace(1,2,5)
print(a)
np.sum(a)

[1.   1.25 1.5  1.75 2.  ]


7.5

In [53]:
# np.unique(arr,return_index = true,return_counts =true)
a= np.array([10,20,30,40,50,20])
np.unique(a,return_index = True , return_counts = True)

(array([10, 20, 30, 40, 50]),
 array([0, 1, 2, 3, 4], dtype=int64),
 array([1, 2, 1, 1, 1], dtype=int64))

In [55]:
# horizon and vertical stacking
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
a

array([1, 2, 3, 4])

In [56]:
b

array([5, 6, 7, 8])

In [ ]:
''' 
'''